//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TierSponsors_Console.srTierSponsorsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/TierSponsors_Service")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srTierSponsorsService.ITierSponsorsService")]
    public interface ITierSponsorsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITierSponsorsService/GetData", ReplyAction="http://tempuri.org/ITierSponsorsService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITierSponsorsService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ITierSponsorsService/GetDataUsingDataContractResponse")]
        TierSponsors_Console.srTierSponsorsService.CompositeType GetDataUsingDataContract(TierSponsors_Console.srTierSponsorsService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITierSponsorsService/GetOrganisations", ReplyAction="http://tempuri.org/ITierSponsorsService/GetOrganisationsResponse")]
        string GetOrganisations(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITierSponsorsService/GetOrganisationsByName", ReplyAction="http://tempuri.org/ITierSponsorsService/GetOrganisationsByNameResponse")]
        string GetOrganisationsByName(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITierSponsorsServiceChannel : TierSponsors_Console.srTierSponsorsService.ITierSponsorsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TierSponsorsServiceClient : System.ServiceModel.ClientBase<TierSponsors_Console.srTierSponsorsService.ITierSponsorsService>, TierSponsors_Console.srTierSponsorsService.ITierSponsorsService {
        
        public TierSponsorsServiceClient() {
        }
        
        public TierSponsorsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TierSponsorsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TierSponsorsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TierSponsorsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public TierSponsors_Console.srTierSponsorsService.CompositeType GetDataUsingDataContract(TierSponsors_Console.srTierSponsorsService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public string GetOrganisations(string query) {
            return base.Channel.GetOrganisations(query);
        }
        
        public string GetOrganisationsByName(string name) {
            return base.Channel.GetOrganisationsByName(name);
        }
    }
}
